name: Jekyll site CI

on:
     schedule:
          - cron:  "2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: 
cd $(dirname "$0")
./generate.sh 2>/dev/null | jq . > builds.json.new
