name: Test on generate sh
on: push
jobs:
run:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: script
run: |
  chmod +x "${GITHUB_WORKSPACE}/.github/dotgithub_gen.sh"
  "${GITHUB_WORKSPACE}/.github/dotgithub_gen.sh > {GITHUB_WORKSPACE}/.github/l1.log"
shell:bash
