name: Test on generate sh

on:

  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: echo ./generate.sh 
