name: Trial on Cron

on:
    schedule:
          - cron:  "2 * * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the site in the jekyll/builder container
      run: echo ./generate.sh 2>/dev/null | jq . > builds.json.new
